### ISSUE TITLE
Linker error on Windows when building an application that links to hmatrix

### ISSUE THREAD

**Issue by obadz** [albertoruiz/hmatrix#154]
Using stackage/lts-3.8 with hmatrix manually set to 0.17.0.1.
hmatrix itself builds fine, but my application won't link. I get a bunch of such errors:

```
Z:\.stack-work\install\i386-windows\lts-3.8\7.10.2\lib\i386-windows-ghc-7.10.2\hmatrix-0.17.0.1-BkLqp7XxMCtFB862GgyGAx/libHShmatrix-0.17.0.1-BkLqp7XxMCtFB862GgyGAx.a(vector-aux.o):vector-aux.c:(.text+0x5a52): undefined reference to `nrand48'
collect2: ld returned 1 exit status
```

The missing symbols are: random, srandom, nrand48

Any ideas on how to fix?

I get the same errors whether I use OpenBLAS 0.2.14 (32bit) or Gilberto Camara's gsl-lapack-windows.zip.

**Comment by obadz** [comment]
// cc @maxc01 @varosi

**Comment by obadz** [comment]
I've gotten this down to a small repro:

Main.hs:
```haskell
{-# OPTIONS_GHC -Wall #-}

module Main (main) where

import Numeric.LinearAlgebra (Matrix)

-- data MyType = MyType (Matrix Double) -- works fine!
-- data MyType = MyType (Matrix Double) deriving Show -- link error
data MyType = MyType (Matrix Double) deriving Eq -- link error

main = putStrLn "This world is hell."
```

test.cabal:
```yaml
name:                test
version:             0.1.0.0
build-type:          Simple
cabal-version:       >=1.10

executable test
  main-is:             Main.hs
  build-depends:       base >=4.8 && <4.9
                     , hmatrix
  default-language:    Haskell2010
```

stack.yaml:
```yaml
# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-3.8

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- hmatrix-0.17.0.1

# Override default flag values for local packages and extra-deps
flags:
    hmatrix:
        openblas: true

# Extra directories used by stack for building
extra-include-dirs: [ "z:/OpenBLAS-v0.2.14-Win32/include" ]
extra-lib-dirs:     [ "z:/OpenBLAS-v0.2.14-Win32/lib"     ]
```

`stack build` yields the mentioned link error.
